apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: twitter-source
spec:
  env:
    - name: QUERY
      valueFrom:
        configMapKeyRef:
          key: QUERY
          name: twitter-serverless-events-config
    - name: T_CONSUMER_KEY
      valueFrom:
        secretKeyRef:
          key: T_CONSUMER_KEY
          name: twitter-serverless-events-secret
    - name: T_CONSUMER_SECRET
      valueFrom:
        secretKeyRef:
          key: T_CONSUMER_SECRET
          name: twitter-serverless-events-secret
    - name: T_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          key: T_ACCESS_TOKEN
          name: twitter-serverless-events-secret
    - name: T_ACCESS_SECRET
      valueFrom:
        secretKeyRef:
          key: T_ACCESS_SECRET
          name: twitter-serverless-events-secret
  image: pratikmahajan/twitter-stream-source:prod-latest
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Broker
metadata:
  name: default