apiVersion: v1
kind: Secret
metadata:
  name: twitter-serverless-events-secret
  labels:
    app: twitter-source
type: Opaque
data:
  T_CONSUMER_KEY: ###
  T_CONSUMER_SECRET: ####
  T_ACCESS_TOKEN: ###
  T_ACCESS_SECRET: ####