apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: serverless-example-python
spec:
  template:
    spec:
      containers:
        - image: docker.io/pratikmahajan/serverless-example-python
          env:
            - name: APP_PORT
              value: "5050"
          ports:
            - containerPort: 5050
          readinessProbe:
            httpGet:
              path: /

